import Image from "next/image";
import Head from "next/head";
import { Box, Container, Text, VStack } from "@chakra-ui/react";

const Home = () => {
  return (
    <>
      <Head>
        <title>Capital - The Bank Account for Modern Companies</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Box>
        <Container maxW='7xl'>
          <Text color='#efece6' fontSize='70px'>
            Test Cut Price Text
          </Text>
        </Container>

        <VStack></VStack>
      </Box>
    </>
  );
};

export default Home;
